apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRESQL_DATABASE: banking-demo-db
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRESQL_USER: ZGVtb3VzZXI=  # base64-encoded value of "demouser"
  POSTGRESQL_PASSWORD: ZGVtb3Bhc3N3b3Jk  # base64-encoded value of "demopassword"
  POSTGRESQL_ADMIN_PASSWORD: YWRtaW5wYXNzd29yZAo= # base64-encoded value of "adminpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: banking-database
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-database
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: registry.redhat.io/rhel9/postgresql-13
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRESQL_ADMIN_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRESQL_DATABASE
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}