apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRESQL_USER: ZGVtby11c2Vy  # base64-encoded value of "demo-user"
  POSTGRESQL_PASSWORD: ZGVtby1wYXNzd29yZA==  # base64-encoded value of "demo-password"
  POSTGRESQL_ADMIN_PASSWORD: ZGVtby1hZG1pbnVzZXI= # base64-encoded value of "demo-adminuser"