apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRESQL_USER: ZGVtb3VzZXI=  # base64-encoded value of "demouser"
  POSTGRESQL_PASSWORD: ZGVtb3Bhc3N3b3Jk  # base64-encoded value of "demopassword"
  POSTGRESQL_ADMIN_PASSWORD: ZGVtb2FkbWludXNlcg== # base64-encoded value of "demoadminuser"