apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRESQL_USER: ZGVtby11c2VyCg==  # base64-encoded value of "demo-user"
  POSTGRESQL_PASSWORD: ZGVtby1wYXNzd29yZAo=  # base64-encoded value of "demo-password"
  POSTGRESQL_ADMIN_PASSWORD: ZGVtby1hZG1pbnVzZXIK # base64-encoded value of "demo-adminuser"