apiVersion: v1
kind: Secret
metadata:
  name: pgadmin4-credentials
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AZGVtby5uZXQK  # base64-encoded value of "admin@demo.net"
  PGADMIN_DEFAULT_PASSWORD: YWRtaW5wYXNzd29yZAo=  # base64-encoded value of "adminpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
spec:
  selector:
    app: pgadmin4
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pgadmin4-route
spec:
  to:
    kind: Service
    name: pgadmin4
    weight: 100
  port:
    targetPort: 8089
#  tls:
#    termination: edge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  labels:
    app: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
        - name: pgadmin4
          image: docker.io/dpage/pgadmin4:6.11
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-credentials
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin4-credentials
                  key: PGADMIN_DEFAULT_PASSWORD
          securityContext:
            allowPrivilegeEscalation: false
#            runAsNonRoot: true
          ports:
            - containerPort: 80